---
title: "Infinium BeadChip Comparison"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{beadchip-comparison}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(yamat)
```

# EPIC v2 vs EPIC/850K

## Manifest from R packages

```{r}
library(tidyverse)
library(IlluminaHumanMethylationEPICanno.ilm10b2.hg19)
library(IlluminaHumanMethylationEPICv2anno.20a1.hg38)
anno_850 <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b2.hg19)
anno_epic_v2 <- getAnnotation(IlluminaHumanMethylationEPICv2anno.20a1.hg38)

# unique probe seqs
length(unique(c(anno_850$ProbeSeqA, anno_850$ProbeSeqB)))

# [1] 1009099


cg_number_epic_v2 <- sapply(anno_epic_v2$Name, function(x) { strsplit(x, split="_")[[1]][1] })
cg_number_epic_v2_850k_common <- intersect(anno_850$Name, cg_number_epic_v2)
length(cg_number_epic_v2_850k_common)

# 722272

anno_epic_v2 %>%
  as.data.frame() %>%
  dplyr::mutate(In_850K=stringr::str_starts(EPICv1_Loci , "cg")) %>%
  dplyr::group_by(In_850K) %>%
  dplyr::summarise(Count=n())

# A tibble: 2 × 2
#   In_850K  Count
#   <lgl>    <int>
# 1 FALSE   205691
# 2 TRUE    724384

anno_epic_v2 %>%
  as.data.frame() %>%
  dplyr::filter(!stringr::str_starts(EPICv1_Loci , "cg")) %>%
  dplyr::group_by(EPICv1_Loci) %>%
  dplyr::summarise(Count=n()) -> anno_epic_v2_new
```

